name: wired2
version: 0.1.0
author: Joris Hermans <hermansj@gmail.com>
description: A modern dependency injection like java spring package (adjusted for Dart 2.x)
homepage: https://github.com/rossalbertson/wired2
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
#  mirrorme: '>=0.2.2 <0.3.0'
  path: ^1.6.2
  mirrorme2: ^0.1.0
  yaml: '>=2.0.1+1 <3.0.0'
dev_dependencies:
#  unittest: '>=0.9.0 <0.9.1'
  test: ^1.0.0
